

CREATE TABLE Sectii (
	id INT PRIMARY KEY,
	tip VARCHAR(128) NOT NULL,
	numar INT NOT NULL
);

CREATE TABLE Complet (
	id INT PRIMARY KEY AUTO_INCREMENT,
	idSectie INT,
	nume VARCHAR(16) NOT NULL,
	FOREIGN KEY (idSectie) REFERENCES Sectii(id)
		ON UPDATE CASCADE ON DELETE SET NULL,
	CONSTRAINT nume_unique UNIQUE(nume)
);

CREATE TABLE Magistrati (
	id INT PRIMARY KEY AUTO_INCREMENT,
	idComplet INT,
	nume VARCHAR(64) NOT NULL,
	prenume VARCHAR(128) NOT NULL,
	CNP CHAR(13) NOT NULL,
	biSerie CHAR(2) NOT NULL,
	biNumar CHAR(6) NOT NULL,
	email VARCHAR(255) NOT NULL,
	user VARCHAR(64) NOT NULL,
	parola CHAR(60) NOT NULL,
	FOREIGN KEY (idComplet) REFERENCES Complet(id)
		ON UPDATE CASCADE ON DELETE SET NULL,
	CONSTRAINT magistrat_unique UNIQUE(CNP, biSerie, biNumar)
);

CREATE TABLE Dosar (
	id BIGINT PRIMARY KEY AUTO_INCREMENT,
	nrDosar INT NOT NULL,
	instanta INT NOT NULL,
	anDosar YEAR NOT NULL DEFAULT (YEAR(CURDATE())),
	idComplet INT,
	materie VARCHAR(128),
	obiect TEXT NOT NULL,
	stadiu VARCHAR(64),
	dataInreg DATETIME NOT NULL DEFAULT (CURDATE()),
	dataModif DATETIME NOT NULL DEFAULT (CURDATE()),
	FOREIGN KEY (idComplet) REFERENCES Complet(id)
		ON UPDATE CASCADE ON DELETE RESTRICT,
	CONSTRAINT dosar_unique UNIQUE(nrDosar, instanta, anDosar)
);

CREATE TABLE Probe (
	id BIGINT PRIMARY KEY AUTO_INCREMENT,
	idDosar BIGINT,
	numar INT,
	nume VARCHAR(32) NOT NULL,
	descriere VARCHAR(255) NOT NULL,
	document VARCHAR(255),
	FOREIGN KEY (idDosar) REFERENCES Dosar(id)
		ON UPDATE CASCADE ON DELETE RESTRICT
);

CREATE TABLE Sedinte (
	id INT PRIMARY KEY AUTO_INCREMENT,
	idDosar BIGINT,
	dataSedinta DATETIME NOT NULL,
	tipSolutie VARCHAR(128) NOT NULL,
	solutie TEXT NOT NULL,
	document VARCHAR(255),
	FOREIGN KEY (idDosar) REFERENCES Dosar(id)
		ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE Persoane (
	id INT PRIMARY KEY AUTO_INCREMENT,
	nume VARCHAR(255) NOT NULL,
	tipPersoana VARCHAR(10) NOT NULL,
	CNP CHAR(13),
	CIF CHAR(12),
	biSerie CHAR(2),
	biNumar CHAR(6),
	tipSocietate VARCHAR(6),
	nrRegComertului VARCHAR(16),
	CAEN CHAR(4),
	IBAN CHAR(24),
	telefon VARCHAR(14) NOT NULL,
	nationalitate VARCHAR(16),
	localitate VARCHAR(32) NOT NULL,
	judet VARCHAR(16) NOT NULL,
	strada VARCHAR(128),
	numarStrada VARCHAR(6),
	bloc VARCHAR(6),
	apartament VARCHAR(6),
	numeRepr VARCHAR(255) NOT NULL,
	userRepr VARCHAR(64) NOT NULL,
	parolaRepr VARCHAR(60) NOT NULL
);

CREATE TABLE Parti (
	id INT PRIMARY KEY AUTO_INCREMENT,
	idPersoana INT,
	idDosar BIGINT,
	calitate VARCHAR(32) NOT NULL,
	FOREIGN KEY (idPersoana) REFERENCES Persoane(id)
		ON UPDATE CASCADE ON DELETE RESTRICT,
	FOREIGN KEY (idDosar) REFERENCES Dosar(id)
		ON UPDATE CASCADE ON DELETE CASCADE
);